/**
 * Chunk worker.
 *
 * Holds its own `ColumnStore` whose columns are views over the *same*
 * SharedArrayBuffers the main thread allocated, so generation and lighting
 * write straight into the world with no message payload at all. Only finished
 * mesh vertex data travels back, and that travels as a transfer rather than a
 * copy.
 */

import { ChunkPipeline } from './pipeline.ts';
import { ColumnData, ColumnStore, type ColumnHandle } from './storage.ts';
import type { SectionMeshResult } from './mesher.ts';

export type WorkerRequest =
  | { type: 'init'; seed: number }
  | { type: 'register'; columns: ColumnHandle[] }
  | { type: 'unregister'; columns: Array<{ x: number; z: number }> }
  | { type: 'generate'; id: number; cx: number; cz: number }
  | { type: 'light'; id: number; cx: number; cz: number }
  | { type: 'mesh'; id: number; cx: number; cz: number; sectionY: number };

export type WorkerResponse =
  | { type: 'ready' }
  | { type: 'generated'; id: number; cx: number; cz: number; ok: boolean }
  | { type: 'lit'; id: number; cx: number; cz: number; ok: boolean }
  | {
      type: 'meshed';
      id: number;
      cx: number;
      cz: number;
      sectionY: number;
      result: SectionMeshResult | null;
    };

const store = new ColumnStore();
let pipeline: ChunkPipeline | null = null;

/** Marks a column generated/lit based on what the main thread already knows. */
function ensureFlags(column: ColumnData, generated: boolean, lit: boolean): void {
  column.generated = generated;
  column.lit = lit;
}

self.onmessage = (event: MessageEvent<WorkerRequest>): void => {
  const message = event.data;

  switch (message.type) {
    case 'init': {
      pipeline = new ChunkPipeline(message.seed);
      (self as unknown as Worker).postMessage({ type: 'ready' } satisfies WorkerResponse);
      break;
    }

    case 'register': {
      for (const handle of message.columns) {
        if (store.has(handle.x, handle.z)) continue;
        store.add(new ColumnData(handle.x, handle.z, handle.buffer));
      }
      break;
    }

    case 'unregister': {
      for (const { x, z } of message.columns) store.remove(x, z);
      break;
    }

    case 'generate': {
      if (!pipeline) return;
      const ok = pipeline.generate(store, message.cx, message.cz);
      (self as unknown as Worker).postMessage({
        type: 'generated', id: message.id, cx: message.cx, cz: message.cz, ok,
      } satisfies WorkerResponse);
      break;
    }

    case 'light': {
      if (!pipeline) return;
      // Neighbours may have been generated by a different worker, which never
      // told this one. The shared memory is already correct, so trust the main
      // thread's scheduling and flag them here.
      for (let dz = -1; dz <= 1; dz++) {
        for (let dx = -1; dx <= 1; dx++) {
          const column = store.get(message.cx + dx, message.cz + dz);
          if (column) ensureFlags(column, true, column.lit);
        }
      }
      const ok = pipeline.light(store, message.cx, message.cz);
      (self as unknown as Worker).postMessage({
        type: 'lit', id: message.id, cx: message.cx, cz: message.cz, ok,
      } satisfies WorkerResponse);
      break;
    }

    case 'mesh': {
      if (!pipeline) return;
      const column = store.get(message.cx, message.cz);
      if (column) ensureFlags(column, true, true);

      const result = pipeline.mesh(store, message.cx, message.cz, message.sectionY);

      const transfers: Transferable[] = [];
      if (result) {
        for (const bucket of result.buckets) {
          if (bucket) transfers.push(bucket.vertices.buffer);
        }
      }

      (self as unknown as Worker).postMessage({
        type: 'meshed',
        id: message.id,
        cx: message.cx,
        cz: message.cz,
        sectionY: message.sectionY,
        result,
      } satisfies WorkerResponse, transfers);
      break;
    }

    default:
      break;
  }
};
